export const getAllProducts = () => {
  return [
    {
      id: 'PRODUCT-001',
      slug: 'svt1',
      name: "An Ode to you ",
      category: 'Best Seller',
      price: 150_000,
      stock: 25,
      imageUrl: '/assets/images/svt1.jpg',
      description: `A Study in Scarlet is an 1887 detective novel by British writer Arthur Conan Doyle. The story marks the first appearance of Sherlock Holmes and Dr. Watson, who would become the most famous detective duo in English literature.`,
      vol : "1",
    
    },
    {
      id: 'PRODUCT-002',
      slug: 'svt2',
      name: "Going Seventeen",
      category: 'Best Seller',
      price: 150_000,
      stock: 15,
      imageUrl: '/assets/images/svt2.jpg',
      description: `3rd Mini Album 'Going Seventeen' (SET).`,
      vol : "2",
    },
    {
      id: 'PRODUCT-003',
      slug: 'svt3',
      name: "You Make My Day",
      category: 'Popular',
      price: 120_000,
      stock: 50,
      imageUrl: '/assets/images/svt3.jpg',
      description: `5th Mini Album 'YOU MAKE MY DAY' (Set).`,
      vol : "1",
    },
    {
      id: 'PRODUCT-004',
      slug: 'svt4',
      name: "Semicolon",
      category: 'Popular',
      price: 150_000,
      stock: 45,
      imageUrl: '/assets/images/svt4.jpg',
      description: `Special Album '; [Semicolon]'.`,
      vol : "1",
    },
    {
      id: 'PRODUCT-005',
      slug: 'svt5',
      name: "Seventeen heaven",
      category: 'Best Seller',
      price: 100_000,
      stock: 10,
      imageUrl: '/assets/images/svt5.jpg',
      description: `11th Mini Album 'SEVENTEENTH HEAVEN' (Random).`,
       vol : "1",
    },
    {
      id: 'PRODUCT-006',
      slug: 'svt6',
      name: "Seventeen heaven",
      category: 'Popular',
      price: 108_000,
      stock: 35,
      imageUrl: '/assets/images/svt6.jpg',
      description: `11th Mini Album 'SEVENTEENTH HEAVEN' (Random).`,
       vol : "2",
    },
    {
      id: 'PRODUCT-007',
      slug: 'svt7',
      name: "Seventeen heaven",
      category: 'Best Seller',
      price: 80_000,
      stock: 20,
      imageUrl: '/assets/images/svt7.jpg',
      description: `11th Mini Album 'SEVENTEENTH HEAVEN' (Random).`,
       vol : "3",
    },
    {
      id: 'PRODUCT-008',
      slug: 'svt8',
      name: "Your Choice",
      category: 'Popular',
      price: 150_000,
      stock: 40,
      imageUrl: '/assets/images/svt8.jpg',
      description: `8th Mini Album 'Your Choice' (Random).`,
      vol : "1",
    },

  ]
}